### ISSUE TITLE
Xcode 프로젝트 만들기

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#1]
# Todo 1월 3일까지
- [x] Xcode 프로젝트 만들어서 커밋하기
- [x] TDD
- [x] .gitignore 파일 수정하기
- [x] Readme.md 파일 수정하기

**Comment by jeonguk29** [comment]
너무 좋습니다!!!
