### ISSUE TITLE
[Refactoring] PostMemoModel을 Memo Model로 통합작업

### ISSUE THREAD

**Issue by jeonguk29** [APP-iOS3rd/PJ3T2_Mymory#108]
# 리팩토링

리팩토링 할 코드에 대한 설명
Memo Model과  PostMemoModel의 필드와 타입이 하나 밖에 차이 나지 않습니다!! 그래서 통합작업을 해보려고 합니다.

## Todo
- [ ] PostviewModel Memo Model을 사용하도록 변환
- [ ] MemoService에서 타입을 변환 하는 부분을 통합
- [ ] PostView 알맞은 Memo Model 값을 사용하도록 변
