### ISSUE TITLE
[Feat]카카오로그인 기능 구현

### ISSUE THREAD

**Issue by Ahario** [APP-iOS3rd/PJ3T2_Mymory#117]
# 기능 설명

## 작동해야 하는 기능에 대해서 설명해주세요

카카오톡을 이용한 회원가입과 로그인 기능을 구현하려고 합니다. 
회원가입 후 파이어베이스와 연결을 해야하며 카카오톡 로그인의 토큰값을 파이어베이스의 UID와 연결을 하는것이 가장 포인트인것같습니다.

---

## 디자인에 대하여

![Screenshot 2024-01-26 at 4 32 02 PM](https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/81345604/6d08cfa7-9da0-472a-b0dc-e020f29af6af)

---

# Todo

### 기능
- [ ] 카카오를 통한 회원가입 구현
- [ ] 회원가입 정보를 파이어베이스에 저장
- [x] 카카오를 통한 로그인
