### ISSUE TITLE
[Feat] 사용자 팔로우 & 팔로잉 기능, 각각의 사용자 프로필 보여주기 

### ISSUE THREAD

**Issue by jeonguk29** [APP-iOS3rd/PJ3T2_Mymory#144]
# 기능 설명

작성해야 하는 기능에 대해서 설명해주세요

각각의 메모 작성자의 프로필을 보여주고 팔로우, 팔로잉 기능을 구현해야 합니다.

---

## 디자인에 대하여

가능하면 [피그마링크](피그마 링크)를 통해서 혹은 스크린샷을 통해서 작성해주세요
![image](https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/54401641/29ea956e-2e2c-4afd-9825-6759b95c6f7c)

---

# Todo

## 요구사항
사용자가 DetailView에서 다른 사용자의 Memo를 확인할 때 작성 사용자의 프로필 정보를 표시
작성 사용자의 프로필이동 버튼을 눌렀을 때 작성 사용자의 프로필 보여주기
팔로우, 팔로우 취소 기능을 구현하고 각각의 사용자 별 팔로잉, 팔로워 숫자를 보여주기 

### 프로필 연결
- [x] 사용자가 DetailView에서 다른 사용자의 Memo를 확인할 때 작성 사용자의 프로필 정보를 표시
- [x] 작성 사용자의 프로필이동 버튼을 눌렀을 때 작성 사용자의 프로필 보여주기

### 팔로우, 팔로잉 기능
- [x] 팔로우, 팔로우 취소 기능을 구현하고 각각의 사용자 별 팔로잉, 팔로워 숫자를 보여주기 
- [x] 팔로우 한 사용자를 앱이 재시작해도 기억할 수 있도록 구현
