### ISSUE TITLE
[Feat]소셜미디어 처음 가입시, 소셜미디어 회원가입 페이지로 이동

### ISSUE THREAD

**Issue by Ahario** [APP-iOS3rd/PJ3T2_Mymory#156]
# 기능 설명

처음 소셜미디어로 로그인 가입시, 소셜미디어 회원가입 페이지로 이동하는 기능입니다

---

## 디자인에 대하여

![Screenshot 2024-02-02 at 1 25 26 PM](https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/81345604/af056a20-6333-4231-b366-abaa91b09a8b)

---

# Todo

## 요구사항
- 소셜미디어 회원가입 페이지 생성
- 파이어베이스 데이터베이스를 확인해서 현재 생성된 유저의 UUID 폴더가 없을경우, 신규유저로 인지하는 함수
- 신규유저 특정 완료시, 소셜미디어 회원가입 페이지로 이동, 생성 완료 후 메인페이지로 이동

### 뷰 생성
- [ ] 피그마를 참고해서 뷰생성

### 함수
- [ ] 신규유저로 인지하는 함수
- [ ] 유저 정보제공동의 확인하는 함수
- [ ] 뒤로가기 버튼에 뷰 이동 기능과 유저 소셜미디어 토큰 삭제 함수
