### ISSUE TITLE
[Refactoring] MyPageViewModel 분리 작업 및 폴더, 파일 이름 수정 작업

### ISSUE THREAD

**Issue by jeonguk29** [APP-iOS3rd/PJ3T2_Mymory#160]
# 리팩토링
MyPage와 관련된 상위, 하위 뷰를 재활용 가능하게 만들고 ViewModel을 분리해서 사용하도록 만들기

## 요구사항
- ViewModel 분리
- 관련 View 재활용 가능하게 만들기
- 폴더, 파일, 클래스, 구조체 이름 변경

## Todo
- [x] 프로토콜 지향 패러다임에 맞춰 MyPageViewModel 분리
- [x] 관련 View 재활용 가능하게 만들기
- [x] 폴더, 파일, 클래스, 구조체 이름 변경
