### ISSUE TITLE
MyPage, OtherUser Profile 분리 작업

### ISSUE THREAD

**Issue by jeonguk29** [APP-iOS3rd/PJ3T2_Mymory#186]
# 리팩토링

현재 공용으로 사용되고 있는 ProfileView를 (MyPage, OtherUser)View로 각각 분리하고 ViewModel을 분기 처리하는 부분을
단일 View 단일 ViewModel 구조로 변경  

## 요구사항
- ProfileView를 MyPage, OtherUser View로 각각 분리
- MyPage, OtherUser View는 각각의 단일 ViewModel을 가지도록 수정 
- OtherUserView에서 내가 작성한 메모라도 해당 View, ViewModel을 활용하여 처리

## Todo
- [x] ProfileView를 MyPage, OtherUser View로 각각 분리
- [x] MyPage, OtherUser View는 각각의 단일 ViewModel을 가지도록 수정 
- [x] OtherUserView에서 내가 작성한 메모라도 해당 View, ViewModel을 활용하여 처리
- [x] 최대한 프로토콜 지향 패러다임을 채택한 재활용 뷰를 살리기
