### ISSUE TITLE
[Feat] 프로필 수정

### ISSUE THREAD

**Issue by Seobe95** [APP-iOS3rd/PJ3T2_Mymory#192]
# 기능 설명
프로필 수정 관련 기능을 개발합니다.

- 프로필 변경 시 storage에서 이전의 이미지를 삭제하는 로직 구현
- 사용자 이름 변경 로직 추가
- 디자인 최신화 작업

---

## 디자인에 대하여
<img width="171" alt="스크린샷 2024-02-07 오후 1 37 12" src="https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/79817557/f9e50b4d-c444-4b2f-99f5-13b8f52e535d">

이 부분에서 사진, 이름만 구현

---

# Todo

### 기능
- [x] 프로필 변경 시 storage에서 이전의 이미지를 삭제하는 로직 구현
- [x] 사용자 이름 변경 로직 추가
- [x] 디자인 최신화 작업
