### ISSUE TITLE
[Refactoring] 1.0 버전 강사님 피드백 사항 - 메인뷰 관련

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#235]
## Todo
- [x] 메인 맵 뷰 On appear 할 때 한 번 refresh
- [x] 메인뷰 스크롤 마진
- [x] km 단위 1줄로만 하게 >  minWidth 추가
- [x] 메인 뷰 주소 오른쪽 리프레시
- [x] 필터 초기화하기 버튼 위치 변경 및 버튼디자인
- [x] 주소 찾기 실패 시 애플 내부 프레임워크로 재시도
