### ISSUE TITLE
[Refactoring]1.0 버전 강사님 피드백 사항 - 디테일뷰 관련

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#236]
## Todo
- [x] 다음글 이전글 버튼 디자인 변경
- [x] 디테일뷰 하트 리본 3dots 너무 가까움
- [x] 디테일뷰가 무조건 첫 번째 메모부터 보여지는 현상 ( 4번째 메모를 선택해도 첫 번째부터 보여줌 )
- [x] 피그마 최신화도 부탁드려요! (사진)
- [x] 멀리있는 메모 디테일뷰 scrollable 하게
