### ISSUE TITLE
[Refactoring] 1.0 버전 강사님 피드백 사항 - 로그인뷰 관련

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#237]
## Todo
- [x] 로그인 버튼이 빨간색임,,,
- [ ] 로그인뷰에서 KeyboardDismiss > forcusstate 활용해서 수정
- [x] 로그인 과정 오류!!!
