### ISSUE TITLE
[Refactoring] 1.0 버전 강사님 피드백 사항 - 디자인 관련

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#238]
## Todo
- [x] 다음글 이전글 버튼 디자인 변경
- [ ] 마커 디자인의 가시성
- [ ] 메인컬러와 텍스트흰색의 가독성
