### ISSUE TITLE
[Refactoring] 기타 자잘하게 수정 필요한 사항들

### ISSUE THREAD

**Issue by xohxe** [APP-iOS3rd/PJ3T2_Mymory#270]
# 리팩토링

리팩토링 할 코드에 대한 설명

## 요구사항
- UX개선
- 기타 오류들을 확인하고 고쳐내자.
 
## Todo
- [x] 메인 지도뷰에서 리스트뷰 클릭 시, 리스트만 보여주기 -> 이에따른 커뮤니티뷰 탭 분리
- [ ] 빌딩명 수정하기
- [ ] 핀 체크되면 기울어지게 애니메이션 주면 좋을듯
- [ ] 폰트 Import안된거 확인 및 새로운 폰트추가?(용량작은거로)
- [ ] 메모지 추가
- [ ] 좋아요 수 표기

**Comment by Ahario** [comment]
개인적으로 설정 -> 폰트에서 폰트 변경리스트에서 박스를 터치해서 변경이 아닌 그 폰트 항목을 클릭시 변경되는걸로 고치면 편할것같습니다.

**Comment by xohxe** [comment]
> 개인적으로 설정 -> 폰트에서 폰트 변경리스트에서 박스를 터치해서 변경이 아닌 그 폰트 항목을 클릭시 변경되는걸로 고치면 편할것같습니다.

오 좋습니다. 해당 부분도 반영해볼게요 :)
